SELECT 
    '1001' as id,
    ZONAS_SUBZONA.ID_ZONA1 as cod,
    ZONAS_SUBZONA.UNZONAS_DESCRIPCION as 'desc'
FROM ZONAS_SUBZONA
WHERE (ZONAS_SUBZONA.ID_ZONA1 = ZONAS_SUBZONA.ID_ZONA)
UNION ALL
SELECT
    '1002' as id,
    ZONAS_SUBZONA.ID_ZONA1 as cod,
    ZONAS_SUBZONA.UNZONAS_DESCRIPCION as 'desc'
FROM ZONAS_SUBZONA
WHERE (ZONAS_SUBZONA.ID_ZONA2 = ZONAS_SUBZONA.ID_ZONA);