SELECT  
    T1.CODIGO AS cod, 
    CASE 
    WHEN T1.DIRECCION_1 != '' THEN T1.DIRECCION_1 
    WHEN T1.DIRECCION_2 != '' THEN T1.DIRECCION_1 
    WHEN T1.DIRECCION_3 != '' THEN T1.DIRECCION_2 
    END AS coddireccion, 
    CASE 
    WHEN T1.DIRECCION_1 != '' THEN 2 
    WHEN T1.DIRECCION_2 != '' THEN 1 
    WHEN T1.DIRECCION_3 != '' THEN 0 
    END AS tdireccion, 
    CASE 
    WHEN T1.DIRECCION_1 != '' THEN T1.DIRECCION_1 
    WHEN T1.DIRECCION_2 != '' THEN T1.DIRECCION_1 
    WHEN T1.DIRECCION_3 != '' THEN T1.DIRECCION_2 
    END AS domicilio,  
    T2.UNCIUDAD_DESCRIPCION as ciudad, 
    T3.UNDPTO_DESCRIPCION as prov, 
    CASE 
    WHEN T1.DIRECCION_1 != '' THEN T1.CLI_ZONA 
    WHEN T1.DIRECCION_2 != '' THEN T1.CLI_ZONA_1 
    WHEN T1.DIRECCION_3 != '' THEN T1.CLI_ZONA_2 
    END AS cp /*Verificar*/, 
    T4.UNPAIS_DESCRIPCION as pais, 
    '' as ind1, 
    '' as ind2, 
    '' as ind3 
FROM  
    TERCEROS AS T1 
    inner join CIUDADES AS T2 on T1.CIUDAD_CORRESP = T2.ID_CIUDAD 
    inner join DEPARTAMENTOS AS T3 on T1.DPTO_CORRESP = T3.ID_DPTO 
    inner join PAISES AS T4 on T1.PAIS_CORRESP = T4.ID_PAIS 
    inner join CONTRATOS AS T5 ON T5.ID_TERC = T1.Codigo AND T5.ID_EMP IN('01','02') 
WHERE 
    (T1.DIRECCION_1 != '' or  
    T1.DIRECCION_2 != '' or  
    T1.DIRECCION_3 != '' );