SELECT 
    T.CODIGO AS codcli, 
    SUBSTRING(CXC.ID_FECHA_CONTAB,1,4) AS anio, 
    SUBSTRING(CXC.ID_FECHA_CONTAB,5,2) AS mes, 
    SUM(CXC.SALDOS_TOT_CARTERA) AS importe 
FROM 
	cgresumen_cxc AS CXC 
    INNER JOIN terceros AS T ON CXC.ID_TERC = T.CODIGO AND CXC.ID_SUC = T.SUCURSAL 
    INNER JOIN cuentas_contab AS CC ON CXC.ID_CUENTA = CC.CODIGO 
WHERE 
    CXC.ID_EMP IN('01','02') 
    AND (CXC.LAPSO_DOC < SUBSTRING(CURDATE() + 0,1,6)) 
GROUP BY 
	T.CODIGO, 
	SUBSTRING(CXC.ID_FECHA_CONTAB,1,4), 
    SUBSTRING(CXC.ID_FECHA_CONTAB,5,2) 
ORDER BY 
	CXC.ID_TERC, 
	SUBSTRING(CXC.ID_FECHA_CONTAB,1,4), 
    SUBSTRING(CXC.ID_FECHA_CONTAB,5,2) 
;